# Site settings
title: Bootstrap App Framework
email: gxclarke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Bootstrap App Framework: Build responsive web-based
  applications using Bootstrap.
baseurl: "/bootstrap-app/"
url: "http://getbootstrapapp.com" # the base hostname & protocol for your site
dist: "https://github.com/gxclarke/bootstrap-app/tree/master/dist"
twitter_username: gxclarke
github_username:  gxclarke

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    style: compressed
